{"quota_remaining": 9384, "quota_max": 10000, "has_more": true, "items": [{"view_count": 11, "last_edit_date": 1477937457, "score": 1, "tags": ["python", "selenium", "selenium-webdriver"], "last_activity_date": 1477937457, "is_answered": false, "question_id": 40347534, "creation_date": 1477935644, "answer_count": 0, "link": "http://stackoverflow.com/questions/40347534/selenium-webdriver-window-determined-as-alert-how-to-get-elements-python", "title": "Selenium Webdriver: window determined as alert, how to get elements (Python)", "owner": {"link": "http://stackoverflow.com/users/2757828/litvin", "reputation": 15, "profile_image": "https://www.gravatar.com/avatar/af80d525819f554bcc82186a3f8ef075?s=128&d=identicon&r=PG&f=1", "display_name": "Litvin", "user_id": 2757828, "user_type": "registered"}}, {"view_count": 6, "link": "http://stackoverflow.com/questions/40347954/object-is-not-iterable-error-when-creating-security-group-in-azure", "owner": {"link": "http://stackoverflow.com/users/6866675/avalon", "reputation": 347, "profile_image": "https://www.gravatar.com/avatar/88a3c5a01aedafb5e654dd291c494625?s=128&d=identicon&r=PG&f=1", "display_name": "Avalon", "user_id": 6866675, "user_type": "registered"}, "tags": ["python", "azure", "ansible"], "last_activity_date": 1477937241, "is_answered": false, "score": 0, "question_id": 40347954, "creation_date": 1477937241, "answer_count": 0, "title": "Object is not iterable error when creating security group in Azure"}, {"view_count": 12, "link": "http://stackoverflow.com/questions/40347952/how-do-i-echo-redirected-input-or-at-least-have-a-blank-line-represented", "owner": {"accept_rate": 89, "link": "http://stackoverflow.com/users/759749/stephen", "reputation": 1164, "profile_image": "https://graph.facebook.com/72615249/picture?type=large", "display_name": "Stephen", "user_id": 759749, "user_type": "registered"}, "tags": ["python", "batch-processing"], "last_activity_date": 1477937230, "is_answered": false, "score": 0, "question_id": 40347952, "creation_date": 1477937230, "answer_count": 0, "title": "How do I echo redirected input, or at least have a blank line represented?"}, {"view_count": 12, "link": "http://stackoverflow.com/questions/40347917/how-to-verify-aws-sigv4-signing", "owner": {"accept_rate": 25, "link": "http://stackoverflow.com/users/3380728/user3380728", "reputation": 11, "profile_image": "https://www.gravatar.com/avatar/4d9ebf84e5c8a2440bad7bb9fba2105b?s=128&d=identicon&r=PG&f=1", "display_name": "user3380728", "user_id": 3380728, "user_type": "registered"}, "tags": ["python"], "last_activity_date": 1477937104, "is_answered": false, "score": 0, "question_id": 40347917, "creation_date": 1477937104, "answer_count": 0, "title": "How to verify AWS SigV4 signing"}, {"view_count": 8, "link": "http://stackoverflow.com/questions/40347888/how-can-i-get-use-of-trained-keras-model-to-make-new-predictions", "owner": {"link": "http://stackoverflow.com/users/7096434/kenny-chou", "reputation": 1, "profile_image": "https://graph.facebook.com/884399118333835/picture?type=large", "display_name": "Kenny Chou", "user_id": 7096434, "user_type": "registered"}, "tags": ["python", "machine-learning", "keras", "iris-recognition", "python-iris"], "last_activity_date": 1477937002, "is_answered": false, "score": 0, "question_id": 40347888, "creation_date": 1477937002, "answer_count": 0, "title": "How can I get use of trained Keras model to make new predictions?"}, {"view_count": 10, "link": "http://stackoverflow.com/questions/40347873/saving-setup-pys-location-when-installing-a-python-package", "owner": {"accept_rate": 56, "link": "http://stackoverflow.com/users/3738857/divide-by-zero", "reputation": 577, "profile_image": "https://www.gravatar.com/avatar/e7c44110196e56caa56260d628ab4d9d?s=128&d=identicon&r=PG", "display_name": "divide_by_zero", "user_id": 3738857, "user_type": "registered"}, "tags": ["python", "python-2.7", "setuptools"], "last_activity_date": 1477936944, "is_answered": false, "score": 0, "question_id": 40347873, "creation_date": 1477936944, "answer_count": 0, "title": "Saving setup.py&#39;s location when installing a python package"}, {"view_count": 11, "link": "http://stackoverflow.com/questions/40347856/compile-python-module-in-c-with-lwiringpy", "owner": {"accept_rate": 54, "link": "http://stackoverflow.com/users/1092519/alexandernajafi", "reputation": 983, "profile_image": "https://i.stack.imgur.com/ecA2O.jpg?s=128&g=1", "display_name": "AlexanderNajafi", "user_id": 1092519, "user_type": "registered"}, "tags": ["python", "c", "module", "raspberry-pi"], "last_activity_date": 1477936888, "is_answered": false, "score": 0, "question_id": 40347856, "creation_date": 1477936888, "answer_count": 0, "title": "Compile Python module in C with -lwiringPy"}, {"view_count": 16, "last_edit_date": 1477936728, "score": 0, "tags": ["python", "django", "django-models"], "last_activity_date": 1477936728, "is_answered": false, "question_id": 40347479, "creation_date": 1477935439, "answer_count": 0, "link": "http://stackoverflow.com/questions/40347479/django-add-methods-to-django-db-models", "title": "Django add methods to django.db.models", "owner": {"accept_rate": 76, "link": "http://stackoverflow.com/users/2517452/richard-christensen", "reputation": 997, "profile_image": "https://i.stack.imgur.com/iNIkO.png?s=128&g=1", "display_name": "Richard Christensen", "user_id": 2517452, "user_type": "registered"}}, {"view_count": 31, "last_edit_date": 1477936617, "score": 0, "tags": ["python", "machine-learning", "neural-network", "tensorflow", "python-3.4"], "last_activity_date": 1477936617, "is_answered": false, "question_id": 40314301, "creation_date": 1477695441, "answer_count": 0, "link": "http://stackoverflow.com/questions/40314301/tensorflow-changing-n-classes-to-2-yields-valueerror-shapes-1-and-a", "title": "tensorflow: Changing n_classes to 2 yields &quot;ValueError: Shapes (?, 1) and (?,) are incompatible; &quot;", "owner": {"link": "http://stackoverflow.com/users/6534672/marie", "reputation": 1, "profile_image": "https://www.gravatar.com/avatar/3b3ee68be65ec221f29e534eea9514db?s=128&d=identicon&r=PG", "display_name": "Marie", "user_id": 6534672, "user_type": "registered"}}, {"view_count": 16, "link": "http://stackoverflow.com/questions/40347743/typeerrorrepro-is-not-json-serializable-odoo-v8", "owner": {"accept_rate": 84, "link": "http://stackoverflow.com/users/2089267/neove", "reputation": 941, "profile_image": "https://www.gravatar.com/avatar/44215d587ff1f8bc581d4098bfec2154?s=128&d=identicon&r=PG&f=1", "display_name": "NeoVe", "user_id": 2089267, "user_type": "registered"}, "tags": ["python", "json", "openerp", "odoo-8"], "last_activity_date": 1477936451, "is_answered": false, "score": 0, "question_id": 40347743, "creation_date": 1477936451, "answer_count": 0, "title": "TypeError(repr(o) + &quot; is not JSON serializable&quot;) - Odoo v8"}, {"view_count": 7, "link": "http://stackoverflow.com/questions/40347726/python-3-5-asyincio-and-aiohttp-errno-101-network-is-unreachable", "owner": {"link": "http://stackoverflow.com/users/6744276/random-person-123", "reputation": 1, "profile_image": "https://www.gravatar.com/avatar/dd6ab8a64810d8ca065dec125e80b96c?s=128&d=identicon&r=PG&f=1", "display_name": "random_person_123", "user_id": 6744276, "user_type": "registered"}, "tags": ["python", "python-3.x", "python-asyncio", "aiohttp"], "last_activity_date": 1477936378, "is_answered": false, "score": 0, "question_id": 40347726, "creation_date": 1477936378, "answer_count": 0, "title": "python 3.5 asyincio and aiohttp Errno 101 Network is unreachable"}, {"view_count": 9, "link": "http://stackoverflow.com/questions/40347689/dataframe-describe-suppress-scientific-notation", "owner": {"link": "http://stackoverflow.com/users/6135337/mfabi", "reputation": 1, "profile_image": "https://www.gravatar.com/avatar/f485c69dfe40c241f3f53d63ea27aa1f?s=128&d=identicon&r=PG&f=1", "display_name": "mfabi", "user_id": 6135337, "user_type": "registered"}, "tags": ["python", "pandas", "dataframe"], "last_activity_date": 1477936265, "is_answered": false, "score": 0, "question_id": 40347689, "creation_date": 1477936265, "answer_count": 0, "title": "dataframe.describe() suppress scientific notation"}, {"view_count": 19, "last_edit_date": 1477936215, "score": 0, "tags": ["python", "django", "security"], "last_activity_date": 1477936215, "is_answered": false, "question_id": 37947274, "creation_date": 1466519487, "answer_count": 0, "link": "http://stackoverflow.com/questions/37947274/secure-redirect-capture-source-url", "title": "Secure redirect - Capture source URL", "owner": {"link": "http://stackoverflow.com/users/3609139/nadav", "reputation": 17, "profile_image": "https://i.stack.imgur.com/RsEMG.jpg?s=128&g=1", "display_name": "Nadav", "user_id": 3609139, "user_type": "registered"}}, {"view_count": 10, "link": "http://stackoverflow.com/questions/40347638/hadoop-mapreduce-task-failing-with-143", "owner": {"accept_rate": 92, "link": "http://stackoverflow.com/users/3184332/hudsond7", "reputation": 166, "profile_image": "https://www.gravatar.com/avatar/1428b9f6e8be9c4f72fe895530ec12f2?s=128&d=identicon&r=PG&f=1", "display_name": "hudsond7", "user_id": 3184332, "user_type": "registered"}, "tags": ["python", "hadoop", "mapreduce"], "last_activity_date": 1477936029, "is_answered": false, "score": 1, "question_id": 40347638, "creation_date": 1477936029, "answer_count": 0, "title": "Hadoop mapreduce task failing with 143"}, {"view_count": 9, "link": "http://stackoverflow.com/questions/40347593/python-shell-restarts-when-requests-for-a-url-by-requests-post", "owner": {"link": "http://stackoverflow.com/users/7096396/nan", "reputation": 1, "profile_image": "https://lh3.googleusercontent.com/-5pMGlTk3zec/AAAAAAAAAAI/AAAAAAAAAqY/Ju3x45OEh8E/photo.jpg?sz=128", "display_name": "Nan", "user_id": 7096396, "user_type": "registered"}, "tags": ["python", "python-2.7", "python-requests"], "last_activity_date": 1477935846, "is_answered": false, "score": -2, "question_id": 40347593, "creation_date": 1477935846, "answer_count": 0, "title": "Python shell restarts when requests for a url by requests.post"}, {"view_count": 5, "link": "http://stackoverflow.com/questions/40347592/can-we-see-the-send-nodes-and-the-receive-nodes-in-the-tensorflow-graph", "owner": {"link": "http://stackoverflow.com/users/6770703/jenny", "reputation": 15, "profile_image": "https://www.gravatar.com/avatar/a18dd76cd90b832bc57db7e241a55eb7?s=128&d=identicon&r=PG&f=1", "display_name": "Jenny", "user_id": 6770703, "user_type": "registered"}, "tags": ["python", "tensorflow"], "last_activity_date": 1477935844, "is_answered": false, "score": 0, "question_id": 40347592, "creation_date": 1477935844, "answer_count": 0, "title": "Can we see the Send nodes and the Receive nodes in the tensorflow Graph?"}, {"view_count": 9, "link": "http://stackoverflow.com/questions/40347478/p2p-system-always-getting-same-getaddrinfo-failed-error-11001", "owner": {"link": "http://stackoverflow.com/users/7071086/sankalp-raj", "reputation": 4, "profile_image": "https://lh3.googleusercontent.com/-1xM4lpW7iaU/AAAAAAAAAAI/AAAAAAAAAas/It2rP_VlfwA/photo.jpg?sz=128", "display_name": "Sankalp Raj", "user_id": 7071086, "user_type": "registered"}, "tags": ["python", "p2p"], "last_activity_date": 1477935437, "is_answered": false, "score": 0, "question_id": 40347478, "creation_date": 1477935437, "answer_count": 0, "title": "P2P system always getting same getaddrinfo failed error 11001"}, {"view_count": 24, "last_edit_date": 1477935362, "score": 0, "tags": ["python", "bash", "flask", "mutt"], "last_activity_date": 1477935362, "is_answered": false, "question_id": 40313035, "creation_date": 1477687870, "answer_count": 0, "link": "http://stackoverflow.com/questions/40313035/mutt-in-bash-script-raises-an-error-in-python-flask-application", "title": "Mutt in bash script raises an error in python (flask) application", "owner": {"link": "http://stackoverflow.com/users/6512252/godric", "reputation": 6, "profile_image": "https://www.gravatar.com/avatar/11f0c28192994ae49cff70855340690f?s=128&d=identicon&r=PG&f=1", "display_name": "Godric", "user_id": 6512252, "user_type": "registered"}}, {"view_count": 52, "link": "http://stackoverflow.com/questions/37556888/why-does-paramiko-sporadically-raise-an-exception", "owner": {"accept_rate": 47, "link": "http://stackoverflow.com/users/5132509/regis-may", "reputation": 129, "profile_image": "https://www.gravatar.com/avatar/453dee1b3bacfbb401b476efdda71a34?s=128&d=identicon&r=PG&f=1", "display_name": "Regis May", "user_id": 5132509, "user_type": "registered"}, "tags": ["python", "ssh", "paramiko"], "last_activity_date": 1477935318, "is_answered": false, "score": 0, "question_id": 37556888, "creation_date": 1464734835, "answer_count": 0, "title": "Why does paramiko sporadically raise an exception?"}, {"view_count": 16, "last_edit_date": 1477935291, "score": 1, "tags": ["python", "numpy", "deep-learning", "theano-cuda"], "last_activity_date": 1477935291, "is_answered": false, "question_id": 40346697, "creation_date": 1477932389, "answer_count": 0, "link": "http://stackoverflow.com/questions/40346697/performance-characteristics-of-theano-shared-variables-vs-numpy-ndarray-gpu", "title": "Performance characteristics of theano.shared variables vs numpy.ndarray (GPU)", "owner": {"link": "http://stackoverflow.com/users/3747801/toke-faurby", "reputation": 50, "profile_image": "https://www.gravatar.com/avatar/f0a1f337a871aabf0ee7681a3fb21678?s=128&d=identicon&r=PG&f=1", "display_name": "Toke Faurby", "user_id": 3747801, "user_type": "registered"}}, {"view_count": 5, "last_edit_date": 1477935224, "score": 0, "tags": ["python", "gtk3", "gobject"], "last_activity_date": 1477935224, "is_answered": false, "question_id": 40347002, "creation_date": 1477933620, "answer_count": 0, "link": "http://stackoverflow.com/questions/40347002/which-gobject-type-for-datetime-and-decimal-in-python-gtk3", "title": "Which Gobject Type for datetime and decimal in Python Gtk3", "owner": {"accept_rate": 58, "link": "http://stackoverflow.com/users/1907997/oxidworks", "reputation": 110, "profile_image": "https://www.gravatar.com/avatar/b223fe986d879dbc3b7262ec7f122fa5?s=128&d=identicon&r=PG", "display_name": "oxidworks", "user_id": 1907997, "user_type": "registered"}}, {"view_count": 12, "link": "http://stackoverflow.com/questions/40347419/return-pdf-generated-with-fpdf-in-flask-on-google-app-engine", "owner": {"link": "http://stackoverflow.com/users/6948460/user6948460", "reputation": 11, "profile_image": "https://www.gravatar.com/avatar/74c18381bedfa71e903286af04b5edb9?s=128&d=identicon&r=PG&f=1", "display_name": "user6948460", "user_id": 6948460, "user_type": "registered"}, "tags": ["python", "google-app-engine", "pdf", "flask", "fpdf"], "last_activity_date": 1477935203, "is_answered": false, "score": 0, "question_id": 40347419, "creation_date": 1477935203, "answer_count": 0, "title": "Return PDF generated with FPDF in Flask on google app engine"}, {"view_count": 16, "link": "http://stackoverflow.com/questions/40347362/why-is-my-code-redirecting-to-another-url", "owner": {"link": "http://stackoverflow.com/users/5236121/anubhav-sharma", "reputation": 1, "profile_image": "https://graph.facebook.com/906330676107472/picture?type=large", "display_name": "Anubhav Sharma", "user_id": 5236121, "user_type": "registered"}, "tags": ["python", "web-scraping"], "last_activity_date": 1477934961, "is_answered": false, "score": 0, "question_id": 40347362, "creation_date": 1477934961, "answer_count": 0, "title": "why is my code redirecting to another url?"}, {"view_count": 14, "last_edit_date": 1477934842, "score": 0, "tags": ["python", "python-2.x", "urlparse"], "last_activity_date": 1477934842, "is_answered": false, "question_id": 40346986, "creation_date": 1477933576, "answer_count": 0, "link": "http://stackoverflow.com/questions/40346986/pythons-urlparse-urljoin-removes-path-when-concatenating", "title": "python&#39;s urlparse.urljoin removes path when concatenating", "owner": {"accept_rate": 67, "link": "http://stackoverflow.com/users/2363252/chefarov", "reputation": 445, "profile_image": "https://i.stack.imgur.com/3eA8a.jpg?s=128&g=1", "display_name": "chefarov", "user_id": 2363252, "user_type": "registered"}}, {"view_count": 17, "link": "http://stackoverflow.com/questions/40347303/kivy-plot-and-screen-manager-plot-not-showing-up", "owner": {"accept_rate": 68, "link": "http://stackoverflow.com/users/3608005/moritz", "reputation": 1182, "profile_image": "https://www.gravatar.com/avatar/235dcc1c473c4be1ddec787d32687650?s=128&d=identicon&r=PG", "display_name": "Moritz", "user_id": 3608005, "user_type": "registered"}, "tags": ["python", "kivy"], "last_activity_date": 1477934691, "is_answered": false, "score": 0, "question_id": 40347303, "creation_date": 1477934691, "answer_count": 0, "title": "kivy: plot and screen manager; plot not showing up"}, {"view_count": 33, "last_edit_date": 1477934653, "score": -1, "tags": ["python", "pandas"], "last_activity_date": 1477934653, "is_answered": false, "question_id": 40346400, "creation_date": 1477931284, "answer_count": 0, "link": "http://stackoverflow.com/questions/40346400/list-of-diverse-lists-to-sorted-pandas-data-frame", "title": "List of diverse lists to sorted pandas data frame", "owner": {"accept_rate": 0, "link": "http://stackoverflow.com/users/6459589/spyth", "reputation": 76, "profile_image": "https://i.stack.imgur.com/a6Yzw.jpg?s=128&g=1", "display_name": "SpyTh", "user_id": 6459589, "user_type": "registered"}}, {"view_count": 15, "last_edit_date": 1477934563, "score": 0, "tags": ["python", "sqlalchemy"], "last_activity_date": 1477934563, "is_answered": false, "question_id": 40345319, "creation_date": 1477927659, "answer_count": 0, "link": "http://stackoverflow.com/questions/40345319/query-elements-with-association-object-with-sqlalchemy", "title": "Query elements with association object with SQLAlchemy", "owner": {"link": "http://stackoverflow.com/users/7095828/romain", "reputation": 1, "profile_image": "https://lh4.googleusercontent.com/-OZLeVXVweyE/AAAAAAAAAAI/AAAAAAAAAD8/yK9NkN_Rge0/photo.jpg?sz=128", "display_name": "Romain", "user_id": 7095828, "user_type": "registered"}}, {"view_count": 6, "link": "http://stackoverflow.com/questions/40347232/keyerror-none-when-invoking-python-nosetests", "owner": {"link": "http://stackoverflow.com/users/2134074/tol4trob", "reputation": 127, "profile_image": "https://i.stack.imgur.com/fIRoA.jpg?s=128&g=1", "display_name": "tol4trob", "user_id": 2134074, "user_type": "registered"}, "tags": ["python", "nose"], "last_activity_date": 1477934454, "is_answered": false, "score": 0, "question_id": 40347232, "creation_date": 1477934454, "answer_count": 0, "title": "KeyError: None when invoking python nosetests"}, {"view_count": 17, "link": "http://stackoverflow.com/questions/40347223/how-to-make-sure-that-a-knob-is-added-inside-a-panel", "owner": {"link": "http://stackoverflow.com/users/6452188/arturo", "reputation": 30, "profile_image": "https://www.gravatar.com/avatar/281450ee5040ee1927d22f5adfc6ab6e?s=128&d=identicon&r=PG&f=1", "display_name": "Arturo", "user_id": 6452188, "user_type": "registered"}, "tags": ["python", "nuke"], "last_activity_date": 1477934423, "is_answered": false, "score": 0, "question_id": 40347223, "creation_date": 1477934423, "answer_count": 0, "title": "how to make sure that a knob is added inside a panel?"}, {"view_count": 160, "last_edit_date": 1477934235, "score": 0, "tags": ["python", "google-app-engine", "post", "google-cloud-datastore"], "last_activity_date": 1477934235, "is_answered": false, "question_id": 17774338, "creation_date": 1374423532, "answer_count": 0, "link": "http://stackoverflow.com/questions/17774338/google-app-engine-datastore-post-not-working", "title": "Google App Engine datastore POST not working", "owner": {"accept_rate": 0, "link": "http://stackoverflow.com/users/2560541/user2560541", "reputation": 11, "profile_image": "https://www.gravatar.com/avatar/a342138bc2f44b7531e211298b44706e?s=128&d=identicon&r=PG", "display_name": "user2560541", "user_id": 2560541, "user_type": "registered"}}]}